const movieTypes = {
  SET_FAVORITE: "SET_FAVORITE",
  DELETE_FAVORITE: "DELETE_FAVORITE",
  FETCH_CUSTOMER: "FETCH_CUSTOMER",
  LOADING_CUSTOMER: "LOADING_CUSTOMER",
  ERROR_CUSTOMER: "ERROR_CUSTOMER",
  LOADING: "LOADING",
};

export default movieTypes;
