const userTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  REGISTER_REQUEST: "REGISTER_REQUEST",
  USER_EXITO: "USER_EXITO",
  USER_ERROR: "USER_ERROR",
  CERRAR_SESION: "CERRAR_SESION",
};

export default userTypes;
